# -*- coding: utf-8 -*-

{
    "name" : "TGB Accountance Module",
    "version" : "0.1",
    "author" : "Son Pham",
    "category" : "Generic Modules",
    "depends" : ['base',
                 'stock',
                 'sale',
                 'purchase',
                 'procurement',
                 'stock_location',
                 'sale_stock',
                 'delivery',
                 'account',
                 'account_accountant',
                 ],
    "description": "TGB Account edit report",
    "data": ['account_report.xml',
             'stock_report.xml',
             'res_company_view.xml',
              'delivery_report.xml',
             'delivery_view.xml',
             'partner_view.xml',
             'stock_move_view.xml',
             ],
    'installable': True,
    'auto_install': False,
}
