# -*- coding: utf-8 -*-

{
    "name": "Falcon Customized Module",
    "version": "0.1",
    "author": "Son Pham",
    "category": "Generic Modules",
    "depends": [
        'crm',
        'mail',
        'account_voucher',
        'account_accountant',
        'sale',
        'stock',
        'purchase',
        'hr',
        'account',
        'account_cutoff_base',
        'account_cutoff_prepaid',
        'account_report_company',
        'analytic',
        'auth_signup',
        'base',
        'base_action_rule',
        'base_calendar',
        'base_import',
        'base_setup',
        'base_status',
        'board',
        'decimal_precision',
        'edi',
        'email_template',
        'fetchmail',
        'hr_contract',
        'portal',
        'portal_crm',
        'portal_hr_employees',
        'portal_sale',
        'portal_stock',
        'process',
        'procurement',
        'product',
        'product_warranty',
        'resource',
        'sale_crm',
        'sale_rental',
        'sale_start_end_dates',
        'sale_stock',
        'share',
        'web',
        'web_calendar',
        'web_diagram',
        'web_gantt',
        'web_graph',
        'web_kanban',
        'web_tests',
        'web_view_editor',
        'fleet',

    ],
    "description": "Falcon Customized Module",
    "data": [
        'warehouse_contactor_view.xml',
        'stock_warehouse_view.xml',
        'product_view.xml',
        'falcon_partner_address_view.xml',
        'partner_view.xml',
        'fleet_view.xml',
    ],
    'installable': True,
    'auto_install': False,
}
