{
    "name" : "TGB AudioNote Customization",
    "version" : "0.1",
    "author" : "Son Pham",
    "category" : "Generic Modules",
    "depends" : ['base',
                 'product',
                 'product_variant_multi',
                 'stock',
                 'TGB_rental',
                 'l10n_sg',
                 'TGB_Sale',
                 'account_deposit',
                 ],
    "description": "TGB AudioNote Customization",
    "data": [
        "product_view.xml",
        "sale_order_view.xml",
        "sale_deposit_view.xml",
        "make_deposit_wiz.xml",
        "account_voucher_view.xml",
        "account_invoice_view.xml",
        "stock_view.xml",
        "data/l10n_sg_chart.xml",
        "data/l10n_sg_chart_tax_code.xml",
        "data/l10n_sg_chart_tax.xml",
        "report/delivery_report.xml",
        "report/sale_report.xml",
        "report/invoice_report.xml",
    ],
    'installable': True,
    'auto_install': False,
}
# -*- coding: utf-8 -*-

