# -*- coding: utf-8 -*-

{
    "name" : "TGB Project Construction",
    "version" : "0.1",
    "author" : "TGB",
    "category" : "Generic Modules",
    "depends" : [
                'sale',
                'purchase',
                 'project_costing_sinar',
                 'timesheet_extended',
                 'payroll_extended',
                 'hr_holiday_extended',

                 ],
    "description": "TGB Project Construction",
    "data": [
             "menu.xml",
             "account_invoice.xml",
             "project_order.xml",
             "stock_issue_view.xml",
             "user_view.xml",
             'purchase_view.xml',
             'stock_picking/stock_picking_in.xml',
             'stock_picking/stock_picking_additional_cost.xml',
             'stock_picking/stock_picking_allocation_detail.xml',
             'stock_picking/stock_picking_carrier.xml',
             'stock_picking/stock_picking_service.xml',
             'project_billing/project_billing.xml',
             'project_billing/project_billing_detail.xml',
             'project_billing/project_billing_products.xml',
             'project_billing/project_billing_member.xml',
             'project_billing/project_billing_src.xml',
             'project_billing/project_billing_customer_po.xml',
             'project_claim/project_claim.xml',
             'project_claim/project_claim_detail.xml',
             'project_claim/project_claimable_item_detail.xml',
             'project_claim/ar_credit_note.xml',
             'project_cost_accrual_reversal/project_cost_accrual_reversal.xml',
             'project_cost_accrual_reversal/project_cost_accrual_reversal_d.xml',
             'request_for_customer_po_top_up/request_for_customer_po_top_up.xml',
             'credit_note/credit_note.xml',
             'project_recongition/project_recongition.xml',
             'project_scheduler/project_scheduler.xml',
             'project_scheduler/project_commision_group.xml',
             'project_scheduler/project_customer_contract.xml',
             'project_scheduler/project_phase_group.xml',
             'project_scheduler/project_scheduler_inventory.xml',
             'project_scheduler/project_scheduler_service.xml',
             'requisition_summary/requisition_summary.xml',
             'requisition_summary/project_shipment_mode.xml',
             'requisition_summary/project_shipment_term.xml',
             'requisition_summary/requisition_summary_detail.xml',
             'requisition_summary/requisition_type.xml',
             'construction_purchase_order/construction_purchase_order.xml',
             'construction_purchase_order/construction_payment_term_tenor.xml',
             'construction_purchase_order/construction_purchase_order_lin.xml',
             'construction_purchase_order/phase_sequence.xml',
             'material_requirements_planning/material_requirements_planning.xml',
             'material_requirements_planning/resource_planning_period.xml',
             'material_requirements_planning/resource_requirement_by_mps_vou.xml',
             'material_requirements_planning/weekly_resource_requirement.xml',
             'human_resources/human_resources_view.xml',
             'human_resources/hr_timesheet_sheet_view.xml',
             'sale_make_invoice_advance.xml',

             ],
    'installable': True,
    #"active": True,
    'auto_install': False,
}
