# -*- coding: utf-8 -*-

{
    "name" : "Contract DK Square Management",
    "version" : "0.1",
    "author" : "Son Pham",
    "category" : "Generic Modules",
    "depends" : ['base',
                 'sale',
                 'document',
                 'account',
                 ],
    "description": "TGB DK Square Contract Management",
    "data": [
        "menu.xml",
        "dk_contract/dk_contract.xml",
        "dk_contract/dk_contract_type.xml",
        "dk_contract/dk_location.xml",
        "dk_contract/remark_notice_view.xml",
        "data_import/contract_import.xml",
        "customer_view.xml",
        "account_view.xml",
        "dk_contract/dk_sequence.xml",
        "dk_contract/res_company_view.xml",
        "dk_contract/appointment_view.xml",
        "dk_contract/dk_contract_ir_cron.xml",
        "dk_invoice/dk_invoice.xml",
        "report/contract_report_view.xml",
        "res_company_view.xml",
    ],
    "css":['static/src/css/allign.css'],
    'installable': True,
    'auto_install': False,
}
