# -*- coding: utf-8 -*-

{
    "name": "TGB HRM Module",
    "version": "0.1",
    "author": "Son Pham",
    "category": "Generic Modules",
    "depends": ['sale', 'account', 'hr_payroll', 'hr_holidays', 'hr_timesheet_sheet'],
    "description": "TGB HRM",
    "data": [
        'new_view/hr_holiday_extended/0_hr.holidays_Tree.xml',
        'new_view/hr_holiday_extended/1_hr.holidays_Search.xml',
        'new_view/hr_holiday_extended/2_hr.holidays_Form.xml',
        'new_view/hr_holiday_extended/3_hr.bank.details_Form.xml',
        'new_view/hr_holiday_extended/4_hr.bank.details_Tree.xml',
        'new_view/payroll_extended/5_binary.ir8a.text.file.wizard_Form.xml',
        'new_view/payroll_extended/6_binary.ir8s.text.file.wizard_Form.xml',
        'new_view/hr_holiday_extended/7_board.board_Form.xml',
        'new_view/hr_holiday_extended/8_board.board_Form.xml',
        'new_view/hr_holiday_extended/9_employee.city_Form.xml',
        'new_view/hr_holiday_extended/10_employee.id.type_Form.xml',
        'new_view/hr_holiday_extended/11_employee.id.type_Tree.xml',
        'new_view/hr_holiday_extended/12_employee.news_Form.xml',
        'new_view/hr_holiday_extended/13_employee.news_Search.xml',
        'new_view/hr_holiday_extended/14_employee.news_Tree.xml',
        'new_view/payroll_extended/15_hr.contract_Search.xml',
        'new_view/payroll_extended/16_hr.contract_Tree.xml',
        'new_view/hr_holiday_extended/17_hr.employee_Tree.xml',
        'new_view/hr_holiday_extended/18_hr.employee_Form.xml',
        'new_view/hr_holiday_extended/19_hr.holiday.lines_Form.xml',
        'new_view/hr_holiday_extended/20_hr.holiday.lines_Search.xml',
        'new_view/hr_holiday_extended/21_hr.holiday.lines_Tree.xml',
        'new_view/hr_holiday_extended/22_hr.holiday.public_Form.xml',
        'new_view/hr_holiday_extended/23_hr.holiday.public_Search.xml',
        'new_view/hr_holiday_extended/24_hr.holiday.public_Tree.xml',
        'new_view/hr_holiday_extended/25_hr.holidays_Tree.xml',
        'new_view/hr_holiday_extended/26_hr.holidays_Tree.xml',
        'new_view/hr_holiday_extended/27_hr.holidays_Tree.xml',
        'new_view/hr_holiday_extended/28_hr.holidays.status_Form.xml',
        'new_view/hr_holiday_extended/29_hr.holidays.status_Tree.xml',
        'new_view/hr_holiday_extended/30_hr.holidays.status_Tree.xml',
        'new_view/hr_holiday_extended/31_hr.holidays_Tree.xml',
        'new_view/payroll_extended/32_res.partner.bank_Form.xml',
        'new_view/payroll_extended/33_hr.payslip.employees_Form.xml',
        'new_view/payroll_extended/34_hr.payroll.structure_Form.xml',
        'new_view/payroll_extended/35_hr.payslip_Form.xml',
        'new_view/payroll_extended/36_hr.payslip_Search.xml',
        'new_view/payroll_extended/37_hr.payslip.run_Form.xml',
        'new_view/payroll_extended/38_hr.salary.rule_Form.xml',
        'new_view/payroll_extended/39_hr.salary.rule_Form.xml',
        'new_view/payroll_extended/40_hr.salary.rule_Tree.xml',
        'new_view/timesheet_extended/41_hr_timesheet_sheet.sheet_Form.xml',
        'new_view/hr_holiday_extended/42_inactive.status_Form.xml',
        'new_view/hr_holiday_extended/43_hr.holidays_Form.xml',
        'new_view/hr_holiday_extended/44_hr.holidays_Calendar.xml',
        'new_view/hr_holiday_extended/45_refuse.leave_Form.xml',
        'new_view/hr_holiday_extended/46_res.country_Form.xml',
        'new_view/hr_holiday_extended/47_res.country.state_Form.xml',
        'new_view/timesheet_extended/48_roster.timesheet_Calendar.xml',
        'new_view/timesheet_extended/49_roster.timesheet_Form.xml',
        'new_view/timesheet_extended/50_roster.timesheet_Search.xml',
        'new_view/timesheet_extended/51_roster.timesheet_Tree.xml',
        'new_view/payroll_extended/52_emp.ir8s.text.file_Form.xml',
        'new_view/payroll_extended/53_emp.ir8a.text.file_Form.xml',
        'new_view/payroll_extended/54_employee.country_Form.xml',
        'new_view/payroll_extended/55_employee.country_Tree.xml',
        'new_view/payroll_extended/56_employee.nationality_Form.xml',
        'new_view/payroll_extended/57_employee.nationality_Tree.xml',
        'new_view/payroll_extended/58_hr.contract_Form.xml',
        'new_view/payroll_extended/59_hr.contract.income.tax_Form.xml',
        'new_view/payroll_extended/60_hr.contract.income.tax_Tree.xml',
        'new_view/payroll_extended/61_hr.contribution.register_Form.xml',
        'new_view/payroll_extended/62_hr.employee_Tree.xml',
        'new_view/payroll_extended/63_hr.employee_Form.xml',
        'new_view/payroll_extended/64_res.users_Form.xml',
        'new_view/payroll_extended/65_salary.report.for.exchequer.glcode_Form.xml',
        'new_view/payroll_extended/66_salary.report.for.exchequer.glcode_Tree.xml',
        'new_action/hr_holiday_extended/0_hr.holidays_ir.actions.act_window.xml',
        'new_action/hr_holiday_extended/1_hr.employee_ir.actions.act_window.xml',
        'new_action/hr_holiday_extended/2_inactive.status_ir.actions.act_window.xml',
        'new_action/payroll_extended/3_emp.ir8a.text.file_ir.actions.act_window.xml',
        'new_action/payroll_extended/4_emp.ir8s.text.file_ir.actions.act_window.xml',
        'new_action/hr_holiday_extended/5_hr.holidays_ir.actions.act_window.xml',
        'new_action/timesheet_extended/6_roster.timesheet_ir.actions.act_window.xml',
        'new_action/hr_holiday_extended/7_employee.news_ir.actions.act_window.xml',
        'new_action/hr_holiday_extended/8_employee.news_ir.actions.act_window.xml',
        'new_action/hr_holiday_extended/9_hr.holiday.public_ir.actions.act_window.xml',
        'new_action/hr_holiday_extended/10_refuse.leave_ir.actions.act_window.xml',
        'new_action/timesheet_extended/11_roster.timesheet_ir.actions.act_window.xml',
        'menu/additional_menu.xml'
    ],
    'installable': False,
}
